### PR TITLE
Update test.tf

### PR DESCRIPTION
**Pull request by fatihtokus**
from the code

### CODE REVIEW

**Comment by fatihtokus** [comment]
cmt

**Comment by fatih-tokus-db** [comment]
closed by ACR - 1111111

**Comment by fatih-tokus-db** [comment]
from the code2

**Comment by fatih-tokus-db** [comment]
Closed via ACR Request-1

**Review by fatih-tokus-db — APPROVED** [review]
Approved via ACR Request-2

**Review by fatih-tokus-db — APPROVED** [review]
Approved via ACR Request-1

**Review by fatih-tokus-db — APPROVED** [review]
Approved via ACR Request-1

**Review by fatih-tokus-db — APPROVED** [review]
Approved via ACR Request-3

**Comment by fatih-tokus-db** [comment]
Closed via ACR Request-4

**Review by fatih-tokus-db — APPROVED** [review]
Approved via ACR Request-3

**Comment by fatih-tokus-db** [comment]
Closed via ACR Request-4

**Pull request closed without merging**
